stages:
  - build
  - test
  - deploy

variables:
  PROJECT_DIR: "payment_gateway"

build:
  stage: build
  script:
    - virtualenv --prompt='($PROJECT_DIR)' -q venv
    - virtualenv --relocatable venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
    policy: push
  only:
    refs:
      - develop
      - master
    changes:
      - requirements.txt
  tags:
    - python

test:
  stage: test

  before_script:
    - cp /var/www/$PROJECT_DIR/project/.env $CI_PROJECT_DIR/project
    - cp /var/www/$PROJECT_DIR/project/.coveragerc $CI_PROJECT_DIR/project
    - cd $CI_PROJECT_DIR/project

  script:
    - ls
    - source $CI_PROJECT_DIR/venv/bin/activate
    - python manage.py makemigrations
    - coverage run manage.py test
    - coverage html
    - coverage report
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"

  artifacts:
    paths:
      - htmlcov

  after_script:
    - ls
    - rm $CI_PROJECT_DIR/project/apps/*/migrations/0*.py
    - rm $CI_PROJECT_DIR/project/.env
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
    policy: pull
  only:
    - develop
    - master
  tags:
    - django

staging:
  stage: deploy
  before_script:
    - cd /var/www/$PROJECT_DIR/project/
    - source /var/www/$PROJECT_DIR/venv/bin/activate
  script:
    - ls
    - git pull
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - uwsgi --reload /tmp/$PROJECT_DIR-master.pid
  only:
    - develop
  #    - /^staging-.*$/
  #  except:
  #    - branches
  tags:
    - django
    - staging

production:
  stage: deploy
  before_script:
    - cd /var/www/$PROJECT_DIR/project/
    - source /var/www/$PROJECT_DIR/venv/bin/activate
  script:
    - git pull
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - uwsgi --reload /tmp/$PROJECT_DIR-master.pid
  only:
    - /^release-.*$/
  except:
    - branches
  tags:
    - django
    - release
