include: "http://git.yourblueapi.com/gitlab-ci.yml"

variables:
  PROJECT_DIR: "payment_gateway"

.deploy:
  stage: deploy
  script:
    - git pull
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - python manage.py makemigrations
    - python manage.py migrate
    - uwsgi --reload /tmp/$PROJECT_DIR-master.pid

.test:
  stage: test
  before_script:
    - cp /var/www/$PROJECT_DIR/project/.env $CI_PROJECT_DIR/
    - source $CI_PROJECT_DIR/venv/bin/activate
  script:
    - python manage.py check
    - python manage.py makemigrations
    - coverage run manage.py test
    - coverage html
    - coverage report
  after_script:
    - rm $CI_PROJECT_DIR/.env
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - htmlcov
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
    policy: pull

build:
  extends:
    - .build
    - .staging
  only:
    refs:
      - master
      - develop

test:
  extends:
    - .test
    - .staging
  only:
    refs:
      - master
      - develop


build_staging:
  only:
    - /^release-.*$/

build_prod:
  only:
    - /^release-.*$/

test_staging:
  only:
    - /^release-.*$/

test_prod:
  only:
    - /^release-.*$/
